services:
  #  backend-app:
  #    container_name: backend-app
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    env_file:
  #      - .env
  #    ports:
  #      - 8080:8080
  postgres:
    container_name: main-db
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5050:5432


volumes:
  postgres:
  redis: